// <auto-generated />
namespace Assigment5Diksha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change19));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051213433_Change19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
